
--#############################################################################
--#                             Documentation                                 #
--#############################################################################
--#                                                                           #
--# Description                                                               #
--#     :                                                                     #
--#                                                                           #
--#                                                                           #
--#                                                                           #
--#                                                                           #
--#                                                                           #
--#                                                                           #
--#############################################################################
--#                              Declaration                                  #
--##############################################################################



USE ${DB_WORK}
;

MSCK REPAIR TABLE increment_supply_item
;

INSERT OVERWRITE TABLE ${DB_WORK}.temp_supply_item
  SELECT T1.*
    FROM ${DB_WORK}.current_supply_item T1
    LEFT OUTER JOIN ${DB_WORK}.increment_supply_item T2
    ON (
    T1.employee_sk=T2.employee_sk AND
    T1.document_releaseid=T2.document_releaseid     )
    WHERE
    T2.employee_sk IS NULL AND
    T2.document_releaseid IS NULL 
 UNION
  SELECT
            max_creationtm,
            employee_sk,
            document_releaseid,
            document_versionid,
            document_systemenvironmentcd,
            document_documentid,
            document_alternatedocumentid,
            document_inboundoutboundind,
            document_documentnm,
            document_creationdt,
            document_description_type,
            document_sourceapplicationcd,
            document_targetapplicationcd,
            document_note_type,
            document_gatewaynm,
            document_senderid_qualifiercd,
            document_receiverid_qualifiercd,
            document_routingsystemnm,
            document_internalfiletransferind,
            document_interchangedate,
            document_interchangetime,
            document_externaltargetind,
            document_dataclassification_dataclassificationlevel_code,
            document_dataclassification_dataclassificationlevel_description,
            document_dataclassification_businesssensitivitylevel_code,
            document_dataclassification_businesssensitivitylevel_description,
            document_dataclassification_phidataind,
            document_dataclassification_pcidataind,
            document_dataclassification_ppidataind,
            documentaction,
            document_actiontypecd,
            document_recordtypecd,
            corporationid,
            divisionid,
            distributioncenterid,
            warehouseid,
            corporateitemcd,
            departmentid,
            itemid_upc_upcnbr,
            itemid_upc_upctxt,
            itemid_upccomponents_packind,
            itemid_upccomponents_manufacturerid,
            itemid_upccomponents_salesid,
            itemid_upccomponents_countryid,
            itemid_upccomponents_systemid,
            itemid_upccomponents_checkdigit,
            itemid_gtinid,
            itemid_vendorproductid,
            itemid_manufproductid,
            itemid_systemspecificitemid,
            itemid_rfid,
            itemid_internalitemid,
            itemid_branchitemcd,
            itemid_itemdescription,
            producthierarchy_productgroup_productgroupcd,
            producthierarchy_productgroup_productgroupnm,
            producthierarchy_productcategorycd_productcategorycd,
            producthierarchy_productcategorycd_productcategorynm,
            producthierarchy_productclasscd_productclasscd,
            producthierarchy_productclasscd_productclassnm,
            producthierarchy_productclasscd_retailsectioncd,
            producthierarchy_productsubclasslevel1_productsubclasslevel1cd,
            producthierarchy_productsubclasslevel1_productsubclassleve1nm,
            producthierarchy_productsubclasslevel2_productsubclasslevel2cd,
            producthierarchy_productsubclasslevel2_productsubclasslevel2nm,
            smic_smicgroupcd,
            smic_smiccategorycd,
            smic_smicclasscd,
            smic_smicsubclasscd,
            smic_smicsub_subclasscd,
            productiongrouphierarchy_productgroup_productgroupcd,
            productiongrouphierarchy_productgroup_productgroupnm,
            productiongrouphierarchy_productcategorycd_productcategorycd,
            productiongrouphierarchy_productcategorycd_productcategorynm,
            productiongrouphierarchy_productclasscd_productclasscd,
            productiongrouphierarchy_productclasscd_productclassnm,
            productiongrouphierarchy_productclasscd_retailsectioncd,
            productiongrouphierarchy_productsubclasslevel1_productsubclasslevel1cd,
            productiongrouphierarchy_productsubclasslevel1_productsubclassleve1nm,
            productiongrouphierarchy_productsubclasslevel2_productsubclasslevel2cd,
            productiongrouphierarchy_productsubclasslevel2_productsubclasslevel2nm,
            corpitemreference_upcid,
            corpitemreference_upccomponents_packind,
            corpitemreference_upccomponents_manufacturerid,
            corpitemreference_upccomponents_salesid,
            corpitemreference_upccomponents_countryid,
            corpitemreference_upccomponents_systemid,
            corpitemreference_upccomponents_checkdigit,
            corpitemreference_statuscd,
            corpitemreference_packnutrientind,
            corpitemreference_nutrienviritemcd,
            corpitemreference_prefcicseqnbr,
            corpitemreference_prefciclockind,
            rogitemreference_rogcd,
            rogitemreference_upcid,
            rogitemreference_upccomponents_packind,
            rogitemreference_upccomponents_manufacturerid,
            rogitemreference_upccomponents_salesid,
            rogitemreference_upccomponents_countryid,
            rogitemreference_upccomponents_systemid,
            rogitemreference_upccomponents_checkdigit,
            rogitemreference_statuscd,
            rogitemreference_primaryupcind,
            rogitemreference_retailsectioncd,
            rogitemreference_retailsectionnm,
            rogitemreference_packnutrientind,
            rogitemreference_nutrienviritemcd,
            rogitemreference_hazardousitemind,
            rogitemreference_retailstatusind,
            rogitemreference_optionalorderind,
            rogitemreference_orderguide_newitemind,
            rogitemreference_orderguide_suppressedind,
            rogitemreference_orderguide_displaygroupsuppressedind,
            rogitemreference_itemtypecd,
            rogitemreference_productsourceind,
            rogitemreference_itemondsdind,
            rogitemreference_producttypecd,
            rogitemreference_offinvoiceincostind,
            commongroup_commoncd,
            commongroup_commoncostsubcd,
            commongroup_likeitemcomparecd,
            commongroup_commonretailcd,
            commongroup_commonpromotioncd,
            commongroup_comparisonitemtypecd,
            itemstatus_corpitemstatus_statuscd,
            itemstatus_corpitemstatus_statuseffdt,
            itemstatus_corpitemstatus_createdt,
            itemstatus_warehouseitemstatus_statuscd,
            itemstatus_warehouseitemstatus_statuseffdt,
            itemstatus_warehouseitemstatus_createdt,
            itemdsc_warehouseitemdsc,
            itemdsc_internetitemdsc,
            itemdsc_retailitemdsc,
            itemdsc_vendoritemdsc,
            warehousebuyer_buyerid,
            warehousebuyer_buyernm,
            warehousebuyer_facilityid,
            warehousebuyer_buyerphonenbr,
            warehousebuyer_buyeremailid,
            warehousebuyer_buyercomment,
            vendor_vendorid,
            vendor_vendorsubaccountnbr,
            vendor_warehousevendorid,
            vendor_pacsvendornbr,
            vendor_vendorconversionfactor,
            vendor_vendorupc,
            vendor_vendorproductnbr,
            vendor_vendoritemdimensions_vendorpackcd,
            vendor_vendoritemdimensions_vendorpackcube,
            vendor_vendoritemdimensions_palletlayer,
            vendor_vendoritemdimensions_palletheight,
            vendor_vendoritemdimensions_itemunitnbr,
            vendor_vendoritemdimensions_itemsizenbr,
            vendor_vendoritemdimensions_uomcd,
            vendor_vendorcostareacd,
            vendor_vendorservicelevel,
            vendor_vendornm,
            vendor_vendordunsnbr,
            vendor_leadvendorind,
            vendor_vendorcontact_contactnm,
            vendor_vendorcontact_phonenbr,
            vendor_vendorcontact_emailaddresstxt,
            vendor_address_addressusagetypecd,
            vendor_address_addressline1txt,
            vendor_address_addressline2txt,
            vendor_address_citynm,
            vendor_address_countynm,
            vendor_address_postalzonecd,
            vendor_address_statecd,
            vendor_address_countrycd,
            vendor_address_latitudedegree,
            vendor_address_longitudedegree,
            vendor_address_timezonecd,
            vendor_address_phonenbr,
            vendor_address_faxnbr,
            shelfunitdimensions_shelfunitsizedsc,
            shelfunitdimensions_sizeqty,
            shelfunitdimensions_sizeuomcd,
            shelfunitdimensions_alternatesizeind,
            shelfunitdimensions_alternatesizedsc,
            shelfunitdimensions_itemheight,
            shelfunitdimensions_itemdepth,
            shelfunitdimensions_itemwidth,
            shelfunitdimensions_itempackuomcd,
            shelfunitdimensions_itemwt,
            shelfunitdimensions_itemwtuom,
            shelfunitdimensions_innerpackqty,
            shelfunitdimensions_shelfpackagecd,
            shipunitdimensions_shipunitpacktypecd,
            shipunitdimensions_shipunitpackqty,
            shipunitdimensions_shipunitwt,
            shipunitdimensions_shipunitwtuomcd,
            storageunitdimensions_warehouseunitwidth,
            storageunitdimensions_warehouseunitlength,
            storageunitdimensions_warehouseunitheight,
            storageunitdimensions_warehousecube,
            storageunitdimensions_warehousemeasureuomcd,
            storageunitdimensions_warehouseunitwt,
            storageunitdimensions_warehouseunitwtuomcd,
            storageunitdimensions_palletlayer,
            storageunitdimensions_palletheight,
            storageunitdimensions_palletstacklimitnbr,
            warehousestationid,
            brand_brandcd,
            brand_brandnm,
            usage_itemusageind,
            usage_itemusagetypecd,
            billing_billingtypeind,
            billing_multideptbillingind,
            tcacd,
            litreequifactor,
            displayitemind,
            assortedpackind,
            nutrienvirqualitiyind,
            manufacturertypeind,
            tariffitemcd,
            tarifftreatmentcd,
            restricteddrugitemind,
            healthmarkind,
            jurisdictionind,
            bottledepositind,
            bottledepositcd,
            bestballind,
            incompatibilitycd,
            scalepretextind,
            cool_countryoforiginitemind,
            cool_countryoforiginlabelingclasscd,
            biologicalterroractind,
            haccpcd,
            ethnicitemtypecd,
            seasonalitemtypecd,
            seasonalitemtypenm,
            specialpackagingtypecd,
            organicitemind,
            onetimebuyind,
            branchitemcd,
            chargecustomerind,
            alternatecic,
            substitutecic,
            dealind,
            restricteditemind,
            fullcasepack,
            productionweight,
            selecteditemcd,
            randomweightcd,
            shelflifedys,
            pulldateind,
            onorderingind,
            ordermodelcd,
            forcedqty,
            backorderedqty,
            itemleadtime,
            orderpackqty,
            buyercasecube,
            seasonalweeknbr,
            itemclasscd,
            supplysourcetype,
            cmrnbr,
            itemhandlingcd,
            staterestrictions,
            dsdreceivingind,
            specialmessagecd,
            butterfatpercent,
            stackabilitycd,
            safetystockqty,
            initialorderqty,
            overseasreferencenbr,
            promotionalorderdt,
            investmentorderdt,
            warehouseinterfaceind,
            warehouselotcd,
            rebillpartyind,
            internetitemind,
            buyingprocesscd,
            purchaserid,
            itemsetnbr,
            transferlevelcd,
            transferlevelmethodid,
            picktolightcaseunitqty,
            picktolightfullpalletind,
            scanitemind,
            warehousealtid,
            distributioncenteraltid,
            orgentitytype,
            orgentityvalue,
            orgentitynm,
            defaultwarehouseitemind
        FROM (SELECT *,
     MAX(creationtm) OVER (PARTITION
   BY employee_sk ,document_releaseid ) AS max_creationtm
            FROM ${DB_WORK}.increment_supply_item) AS SUB
    WHERE creationtm = max_creationtm;


--#############################################################################
--#                                   End                                     #
--#############################################################################

